### ISSUE TITLE
Update to material design icons 3.8.95

### ISSUE THREAD

**Issue by bartektartanus** [ziofat/material_design_icons_flutter#11]
Or if you have script for updating you can push it, so anyone can fork and update package locally. And then of course submit pull request :)

**Comment by ziofat** [comment]
Sorry for the delay. I was kinda busy recently.

I added the update script into repository. It was written in JavaScript which I was more familiar with back then. I didn't include them because I didn't want then to be published in pub as well. But it seems not a big deal anyway.

The new version has been published, thanks for your feedback.
