### ISSUE TITLE
icon for tiktok app is missing

### ISSUE THREAD

**Issue by ibrahimsebbane** [ziofat/material_design_icons_flutter#26]
the plugin is so good, but it's missing the tiktok icon

**Comment by ziofat** [comment]
I didn't find an icon for tiktok.

This is a flutter plugin for using [mdi](https://materialdesignicons.com/) in flutter. All the design work is credited to community who contributes to https://github.com/templarian/MaterialDesign.

![image](https://user-images.githubusercontent.com/8521174/91411906-96645280-e87b-11ea-917e-bec2637f8afd.png)

**Comment by ibrahimsebbane** [comment]
Hello, here is the icon of tiktok in the image below

**Comment by ziofat** [comment]
Are you going to post an image or you are mentioning my image? There is no icons in the image I posted. Maybe I used a wrong keyword?

**Comment by ibrahimsebbane** [comment]
Yes i already send you an image that contains the icon for tiktok, if you
didn't receive it then just type: tiktok in google

**Comment by ziofat** [comment]
I might not make it clear. Only icons in [MDI](https://materialdesignicons.com/) will be included in this plugin, because this is an adapter to make those icons work in flutter. You can file an issue in [https://github.com/templarian/MaterialDesign](https://github.com/templarian/MaterialDesign) so maybe it will include `tiktok` as a brand icon in future release, then this plugin will sync with it.

**Comment by ziofat** [comment]
https://github.com/Templarian/MaterialDesign/issues/4956

Wow, I did some search that they will not accept brand icons. So you might want to use [flutter_brand_icons](https://pub.dev/packages/flutter_brand_icons).

**Comment by ibrahimsebbane** [comment]
Ok thanks

**Comment by balibebas** [comment]
> So you might want to use [flutter_brand_icons](https://pub.dev/packages/flutter_brand_icons).

What's the point of using an icon library at all if they don't cover the basics?
