### ISSUE TITLE
Missing cross

### ISSUE THREAD

**Issue by moovida** [ziofat/material_design_icons_flutter#34]
I noticed this looking for some icons, one of which is **cross**. While it is present in the official site:

![image](https://user-images.githubusercontent.com/390250/120461691-804f6980-c39a-11eb-80e3-d1ea1dde2a9d.png)

I couldn't find it in the flutter release. I also tried the web demo you make available and it is not present also there.

Any idea why that happens? Thanks a ton!

**Comment by ItsJimi** [comment]
I don't know in which mdi update the cross icon has been added but I can't find it in [/lib/icon_map.dart](https://github.com/ziofat/material_design_icons_flutter/blob/master/lib/icon_map.dart), maybe the update script have a problem @ziofat?

**Comment by ziofat** [comment]
Sorry for the late response. `cross` icon was added in [this commit](https://github.com/Templarian/MaterialDesign/commit/6089443af1e3b16796a14c04030ea7f527e581af). MDI has its own releasing pattern and this icon has not been added to latest release yet.

MDI is preparing its 6.0 major release so it may be the reason of not publishing any new icons because they use version to represent their icon quantity. New icons will make the version bump to 6.x.

So there is nothing I can do for now, I will follow up when MDI release this icon in its web font library.

**Comment by moovida** [comment]
Thanks for the explanation @ziofat . That makes totally sense. Will close this issue.
