### ISSUE TITLE
Display material_design_icons in IntelliJ

### ISSUE THREAD

**Issue by StefanLobbenmeier** [ziofat/material_design_icons_flutter#7]
Is there any way the icons could also be displayed in IntelliJ? The normal Icons are shown beside the corresponding line. We would probably have to ask the creators of the plugin and edit this generator:
![grafik](https://user-images.githubusercontent.com/36509607/54614750-39952380-4a5d-11e9-82eb-832b24fbb0ad.png)

https://github.com/flutter/flutter-intellij/blob/7f67fa1f4100ca09bebb49725069b1d3e007a748/tool/icon_generator/lib/main.dart

**Comment by ziofat** [comment]
I have never used IntelliJ but I will look into this.

**Comment by huobazi** [comment]
![image](https://user-images.githubusercontent.com/341526/61179276-d776b480-a631-11e9-8c79-88e8cdc388c5.png)
also android studio

**Comment by ziofat** [comment]
And VSCode as well.
![image](https://user-images.githubusercontent.com/8521174/61457297-987e9100-a99a-11e9-86ae-0435464e4b0c.png)

**Comment by StefanLobbenmeier** [comment]
@ziofat I found an IntelliJ Plugin that already supports Icons from https://pub.dev/packages/flutter_vector_icons - a library that looks like it is a superset of the icons here. Do you think it makes sense to fork https://github.com/marius-h/flutter_enhancement_suite and add support for this package - or would it make more sense to merge this package with the https://pub.dev/packages/flutter_vector_icons package. 

Sorry for putting you in such a position. I really don't want to disrespect this package and the work you've put in it. On the other hand - if you're using this package only as a part of another project it would probably be nice to resolve this redundancy.
On the other hand it might also be worthwhile to keep this package as a more "lightweight" font for people that don't want to bloat their app with too many unused fonts.

What do you think?

**Comment by ziofat** [comment]
@StefanLobbenmeier Hi, sorry it takes long to reply you. I was kinda in a busy situation.

I am very glad to see `flutter_enhancement_suit` has already support this package.

`flutter_vector_icons` have multiple iconsets including mdi icons. I think it might result in heavier bundle weight in production because all font files were declared in `pubspec.yml`. It is nice to have multiple iconsets together if you actually using them, but I will keep maintaining this little project for who only use mdi icons.

I am closing this issue as `flutter_enhancement_suit` support this.
